// Builds figma/plugin/code.js = extract.js (without its CommonJS export) + main.js.
const dir = new URL("../figma/", import.meta.url);
const extract = (await Bun.file(new URL("extract.js", dir)).text()).replace(/^if \(typeof module.*$/m, "");
const main = await Bun.file(new URL("plugin/main.js", dir)).text();
await Bun.write(new URL("plugin/code.js", dir), `// Generated by tools/build_figma.ts. Edit extract.js / plugin/main.js instead.\n${extract}\n${main}`);
console.log("figma/plugin/code.js written");
const template = await Bun.file(new URL("plugin/ui.source.html", dir)).text();
const guide = await Bun.file(new URL("plugin/tag-guide.js", dir)).text();
const css = await Bun.file(new URL("plugin/tag-guide.css", dir)).text();
await Bun.write(new URL("plugin/ui.html", dir), template.replace('/* TAG_GUIDE_STYLE */', () => css).replace('<!-- TAG_GUIDE_SCRIPT -->', () => `<script>\n${guide}\n</script>`));
console.log("figma/plugin/ui.html written");
