"""Generate studio/src/FontMetrics.luau from the fonts bundled with Roblox Studio.

Usage: python tools/gen_fonts.py
Reads %LOCALAPPDATA%/Roblox/Versions/<latest>/content/fonts.
"""
import json
import os
import struct
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "studio" / "src" / "FontMetrics.luau"


def find_fonts_dir() -> Path:
    versions = Path(os.environ["LOCALAPPDATA"]) / "Roblox" / "Versions"
    dirs = [d / "content" / "fonts" for d in versions.iterdir() if (d / "content" / "fonts" / "families").is_dir()]
    return max(dirs, key=lambda d: d.stat().st_mtime)


def read_metrics(path: Path):
    data = path.read_bytes()
    count = struct.unpack(">H", data[4:6])[0]
    tables = {}
    for i in range(count):
        tag, _, off, _ = struct.unpack(">4sIII", data[12 + 16 * i : 28 + 16 * i])
        tables[tag.decode("latin-1")] = off
    upm = struct.unpack(">H", data[tables["head"] + 18 : tables["head"] + 20])[0]
    h = tables["hhea"]
    asc, desc, gap = struct.unpack(">hhh", data[h + 4 : h + 10])
    o = tables["OS/2"]
    version = struct.unpack(">H", data[o : o + 2])[0]
    cap = struct.unpack(">h", data[o + 88 : o + 90])[0] if version >= 2 else int(asc * 0.7)
    return {"upm": upm, "asc": asc, "desc": -desc, "gap": gap, "cap": cap}


def main():
    fonts = find_fonts_dir()
    families = {}
    for fam_file in sorted((fonts / "families").glob("*.json")):
        fam = json.loads(fam_file.read_text(encoding="utf-8"))
        faces = []
        for face in fam["faces"]:
            asset = face["assetId"].replace("rbxasset://fonts/", "")
            font_path = fonts / asset
            if not font_path.exists():
                continue
            m = read_metrics(font_path)
            em = m["asc"] + m["desc"]
            faces.append(
                {
                    "weight": face["weight"],
                    "style": face["style"],
                    # Fractions of the Roblox line box (TextSize), which spans asc+desc.
                    "base": round(m["asc"] / em, 4),
                    "cap": round(m["cap"] / em, 4),
                    # asc+desc in em units; Figma's AUTO line height uses this.
                    "line": round(em / m["upm"], 4),
                    "ascEm": round(m["asc"] / m["upm"], 4),
                }
            )
        if faces:
            families[fam["name"]] = {"id": fam_file.stem, "faces": faces}

    lines = [
        "-- Generated by tools/gen_fonts.py. Do not edit by hand.",
        "-- Keyed by the family name Figma uses. `base`/`cap` are fractions of the Roblox",
        "-- line box; `line` and `ascEm` are in em units of the font size.",
        "return {",
    ]
    for name, fam in sorted(families.items()):
        faces = ", ".join(
            "{weight = %d, style = %s, base = %s, cap = %s, line = %s, ascEm = %s}"
            % (f["weight"], json.dumps(f["style"]), f["base"], f["cap"], f["line"], f["ascEm"])
            for f in fam["faces"]
        )
        lines.append("\t[%s] = {id = %s, faces = {%s}}," % (json.dumps(name), json.dumps(fam["id"]), faces))
    lines.append("}")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"{len(families)} families -> {OUT}")


if __name__ == "__main__":
    main()
